hugoblox:
  schema: "2.0"
  identity:
    name: Jinho Kim
    type: person
    tagline: Economics PhD Candidate | UC Davis
    description: Jinho Kim is a PhD candidate in Economics at UC Davis.
    organization: UC Davis
  theme:
    mode: light
    pack: contrast
    colors:
      primary: "#0f3599"
      secondary: "#ffffff"
      neutral: "gray"
    colors_light:
      neutral: ""
      primary: ""
    surfaces:
      header: {}
    colors_dark:
      neutral: ""
      secondary: "#0e172a"
      primary: slate
  typography:
    font: sans
    size: lg
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: false
  copyright:
    notice: © 2026 Jinho Kim. All rights reserved.
    license:
      type: custom
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
